apiVersion: v1
kind: Service
metadata:
  name: nameserver
spec:
  selector:
    app: nameserver
  ports:
  - name: udp
    targetPort: 1053
    port: 53
    protocol: UDP
  - name: tcp
    targetPort: 1053
    port: 53
    protocol: TCP 
